name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
          cache: true
          # cache-dependency-path: go.sum
      
      - name: Test
        run: make test

      - name: Unit Test for CTFd/ctfcli
        uses: xryuseix/ctfcli-unit-test@main
        with:
          target_directory: example