name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum
      
      - name: Test
        run: make test

      - name: ctfcli-unit-test
        continue-on-error: true # failture test is included
        uses: xryuseix/ctfcli-unit-test@8f2d231dabd41d41bffe0cd982dd546e402725c3 # v2.0.1
        with:
          target_directory: example
          config_file: example/config.yaml
